export { JobRequirementExtractionSchema } from "./requirements/jobRequirementExtractionSchema";
export type { JobRequirementExtractionDraft, ExtractedRequirement } from "./requirements/jobRequirementExtractionSchema";
export { extractJobRequirements, JobRequirementExtractionValidationError } from "./requirements/extractJobRequirements";
export { ensureJobRequirements, type JobForRequirements } from "./requirements/ensureJobRequirements";
export { buildResumeSnapshot, type EvidenceSourceType, type EvidenceCatalogEntry, type ResumeSnapshot } from "./optimization/buildResumeSnapshot";
export { OptimizeResumeSchema, SelectedBulletSchema } from "./optimization/optimizeResumeSchema";
export type { OptimizeResumeDraft, SelectedBulletDraft } from "./optimization/optimizeResumeSchema";
export { optimizeResume, OptimizeResumeValidationError } from "./optimization/optimizeResume";
export type { RequirementForPrompt, OptimizeResumeInput } from "./optimization/optimizeResume";
export { applyDeterministicGuard, type AppliedBullet, type RejectedClaim, type GuardResult } from "./optimization/applyDeterministicGuard";
export { scoreKeywordCoverage, type RequirementTerm, type KeywordCoverageResult } from "./evaluation/scoreKeywordCoverage";
export { cosineSimilarity, scoreSemanticSimilarity } from "./evaluation/scoreSemanticSimilarity";
